sonar.projectKey=steflebelge_bobapp-front-angular
sonar.organization=steflebelge
sonar.sources=src
sonar.exclusions=**/*.spec.ts,node_modules/**
sonar.tests=src
sonar.test.inclusions=**/*.spec.ts
sonar.javascript.lcov.reportPaths=coverage/bobapp/lcov.info
